# Generated by Django 3.1.6 on 2021-03-20 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteAuthor',
            fields=[
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='yonder.author')),
            ],
            bases=('yonder.author',),
        ),
        migrations.CreateModel(
            name='RemoteNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteAuthorFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonder.author')),
                ('remote_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_friends', to='yonder.remoteauthor')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteAuthorFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_following', to='yonder.author')),
                ('remote_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_followers', to='yonder.remoteauthor')),
            ],
        ),
        migrations.AddField(
            model_name='remoteauthor',
            name='remote_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonder.remotenode'),
        ),
        migrations.CreateModel(
            name='AuthorFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yonder.author')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='yonder.author')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='yonder.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='yonder.author')),
            ],
        ),
    ]
