# Generated by Django 3.1.6 on 2021-03-23 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0002_authorfollower_authorfriend_remotenode'),
        ('yonder', '0002_inbox'),
    ]

    operations = [
    ]
