# Generated by Django 3.1.6 on 2021-03-25 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yonder', '0003_merge_20210323_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='our_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='our_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotenode',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remotenode',
            name='host',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
