# Generated by Django 3.1.6 on 2021-03-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0004_auto_20210325_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS')], default='PUBLIC', max_length=8),
        ),
    ]
