# Generated by Django 3.1.6 on 2021-03-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0005_auto_20210331_0014'),
        ('yonder', '0005_like'),
    ]

    operations = [
    ]
