# Generated by Django 3.1.6 on 2021-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0006_merge_20210331_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
