# Generated by Django 3.1.6 on 2021-04-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yonder', '0007_auto_20210404_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.JSONField(),
        ),
    ]
