export const RETREIVE_POSTS_SUBMITTED = "RETREIVE_POSTS_SUBMITTED";
export const RETREIVE_POSTS_ERROR = "RETREIVE_POSTS_ERROR";
export const RETREIVE_POSTS_SUCCESS = "RETREIVE_POSTS_SUCCESS";
export const NEW_POST_SUBMITTED = "NEW_POST_CREATED";
export const NEW_POST_ERROR = "NEW_POST_ERROR";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
