export const RETRIEVE_POSTS_SUBMITTED = "RETRIEVE_POSTS_SUBMITTED";
export const RETRIEVE_POSTS_ERROR = "RETRIEVE_POSTS_ERROR";
export const RETRIEVE_POSTS_SUCCESS = "RETRIEVE_POSTS_SUCCESS";
export const NEW_POST_SUBMITTED = "NEW_POST_CREATED";
export const NEW_POST_ERROR = "NEW_POST_ERROR";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
