export const RETREIVE_POSTS = "RETREIVE_POSTS";
export const NEW_POST_SUBMITTED = "NEW_POST_CREATED";
export const NEW_POST_ERROR = "NEW_POST_ERROR";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
