# Generated by Django 3.1.6 on 2021-03-05 05:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('context', models.CharField(max_length=400)),
                ('summary', models.CharField(max_length=400)),
                ('type', models.CharField(max_length=100)),
                ('object', models.CharField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.author')),
                ('likes', models.ManyToManyField(blank=True, to='accounts.Like')),
                ('posts', models.ManyToManyField(blank=True, to='accounts.Post')),
            ],
        ),
    ]
