export const RETRIEVE_POSTS_SUBMITTED = "RETRIEVE_POSTS_CREATED";
export const RETRIEVE_POSTS_ERROR = "RETRIEVE_POSTS_ERROR";
export const RETRIEVE_POSTS_SUCCESS = "RETRIEVE_POSTS_SUCCESS";

export const NEW_POST_SUBMITTED = "NEW_POST_CREATED";
export const NEW_POST_ERROR = "NEW_POST_ERROR";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";

export const EDIT_POST_SUBMITTED = "EDIT_POST_CREATED";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";

export const DELETE_POST_SUBMITTED = "DELETE_POST_CREATED";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";

export const LIKE_POST_SUBMITTED = "LIKE_POST_CREATED";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";

export const SHARE_POST_SUBMITTED = "SHARE_POST_SUBMITTED";
export const SHARE_POST_ERROR = "SHARE_POST_ERROR";
export const SHARE_POST_SUCCESS = "SHARE_POST_SUCCESS";
