export const RETRIEVE_AUTHOR_SUBMITTED = "RETRIEVE_AUTHOR_SUBMITTED";
export const RETRIEVE_AUTHOR_ERROR = "RETRIEVE_AUTHOR_ERROR";
export const RETRIEVE_AUTHOR_SUCCESS = "RETRIEVE_AUTHOR_SUCCESS";
export const RETRIEVE_AUTHOR_POSTS_SUBMITTED = "RETRIEVE_AUTHOR_POSTS_SUBMITTED";
export const RETRIEVE_AUTHOR_POSTS_ERROR = "RETRIEVE_AUTHOR_POSTS_ERROR";
export const RETRIEVE_AUTHOR_POSTS_SUCCESS = "RETRIEVE_AUTHOR_POSTS_SUCCESS";
