
export const RETRIEVE_INBOX_SUBMITTED = "RETRIEVE_INBOX_SUBMITTED";
export const RETRIEVE_INBOX_ERROR = "RETRIEVE_INBOX_ERROR";
export const RETRIEVE_INBOX_SUCCESS = "RETRIEVE_INBOX_SUCCESS";

export const CLEAR_INBOX_SUBMITTED = "CLEAR_INBOX_SUBMITTED";
export const CLEAR_INBOX_ERROR = "CLEAR_INBOX_ERROR";
export const CLEAR_INBOX_SUCCESS = "CLEAR_INBOX_SUCCESS";

export const RETRIEVE_ALL_AUTHORS_ERROR = "RETRIEVE_ALL_AUTHORS_ERROR";
export const RETRIEVE_ALL_AUTHORS_SUCCESS = "RETRIEVE_ALL_AUTHORS_SUCCESS";