export const RETRIEVE_POST_SUBMITTED = "RETRIEVE_POST_SUBMITTED";
export const RETRIEVE_POST_ERROR = "RETRIEVE_POST_ERROR";
export const RETRIEVE_POST_SUCCESS = "RETRIEVE_POST_SUCCESS";
export const NEW_COMMENT_SUBMITTED = "NEW_COMMENT_SUBMITTED";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_ERROR = "NEW_COMMENT_ERROR";
export const RETRIEVE_COMMENT_LIST_SUBMITTED = "RETRIEVE_COMMENT_LIST_SUBMITTED";
export const RETRIEVE_COMMENT_LIST_SUCCESS = "RETRIEVE_COMMENT_LIST_SUCCESS";
export const RETRIEVE_COMMENT_LIST_ERROR = "RETRIEVE_COMMENT_LIST_ERROR";

export const RETRIEVE_POSTLIKE_SUBMITTED = "RETRIVE_POSTLIKE_SUBMITTED";
export const RETRIEVE_POSTLIKE_SUCCESS = "RETRIVE_POSTLIKE_SUBMITTED";
export const RETRIEVE_POSTLIKE_ERROR = "RETRIVE_POSTLIKE_SUBMITTED";