export const SET_TOKEN = "SET_TOKEN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_AUTHOR = "SET_CURRENT_AUTHOR";
export const UNSET_CURRENT_USER = "UNSET_CURRENT_USER";
